@ECHO OFF
REM DO NOT EDIT THIS FILE. Update the UploadPackage-RunManually.ps1 script instead to adjust the settings used to upload the package to the NuGet gallery.
REM This batch file simply calls the UploadPackage-RunManually.ps1 PowerShell script.
REM Use this to run the PowerShell script without requiring you to explicitly change your PowerShell Execution Policy settings to allow PowerShell scripts to be ran.
SET THIS_SCRIPTS_DIRECTORY=%~dp0
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '%THIS_SCRIPTS_DIRECTORY%UploadPackage-RunManually.ps1'"